language: python
sudo: false
matrix:
  include:
  - python: '2.7'
  - python: '3.4'
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
  - python: '3.8-dev'
    dist: xenial
    sudo: true
  allow_failures:
    - python: '3.8-dev'
before_install:
- pip install -U pip
- pip install -U pytest pytest-cov codecov coverage
install:
- python setup.py install
script:
- python -m pytest tests/
- coverage run setup.py test
after_success:
- codecov

deploy:
  provider: pypi
  user: beardypig
  password:
    secure: XqF4bpRTYUWhT2tn7Omc3ia0odOxk8m2HeaLnGR+v+fmxsyBK9+7eKEiSXkKjR/leesL0Jd7eRj1CYbtQiBfIk4oJHjrZadDE4YLbNYLiVvDIN8SjwhZ0HtjvSN99oFu/euYCUB/Hsv3z9EyYVtZuyP0zvr+h6VrbERVQFHC17wtL4camTTk1Iogs0Psj0qIdbeJ32r3ibCpywW+HAUnbTCOsk3dGM8rHmle0VbwkNqfGxMiOHwBDcOrr7604EA2yczZ4q8O/sRnRwAzloN5DG8uxHN63lmihqYaVYFSjajVXXRzVpqpC4R4lKFoaDdYS05I6P/ueKY3cDkLlQPxB2bZXrpKFVm80VTWH4H2dBspKUjpYb7jRXGSYeLSqItHuEsJZQ7P/MwJzcgeg5wgKBD8zFWbztLOfiv4YGGfYG49borV16Fm+O0gniAe94J50LH6x9xoZW8dPU2I8wDU/JvhwCw/3Yc0QQskP9jWLfdrvCLfVYfshC8/X7XDi5bfjs0gAVaNhRCvDeHMxN+vaybqaSB/sL4spV/hVlpna7Ur++MY+K1jIPQEV+P0eoFJzB/mbxcfRHBYQzBrSGzuLTzJBc8OlTh8vmYXpU6mlyfgX7omLZB0sEsUVg1BRHMoJzE0f1kdMqz3iG75cxaYyhuAtMyTnBRfP0jWpqqJiMs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: beardypig/pymp4
