name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # ubuntu-latest is 22.04 and only supports Python 3.7+, 20.04 only supports 3.5+
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install project
      run: python -m pip install .
    - name: Run tests
      run: python -m pytest tests/
    - name: Run coverage
      run: coverage run setup.py test
    - name: Run codecov
      run: codecov
